fixed Pattern Not Concrete error
-- when declared Initial(), I needed to specify compartment via  <**compart_name>
-- this version working through the 
Traceback (most recent call last):
  File "C:\...\Model-Calibration\run_nextdraft_testmito.py", line 1, in <module>
    from condensed_test_mito import model as md
  File "C:\...\Model-Calibration\condensed_test_mito.py", line 372, in <module>
    Observable('obPoreformers_bound', PoreFormers(bh3=1))
  File "C:\...\envs\baxhax\lib\site-packages\pysb\core.py", line 1974, in __init__
    reaction_pattern = as_reaction_pattern(reaction_pattern)
  File "C:\...\envs\baxhax\lib\site-packages\pysb\core.py", line 1627, in as_reaction_pattern
    return ReactionPattern([as_complex_pattern(v)])
  File "C:\...\envs\baxhax\lib\site-packages\pysb\core.py", line 1518, in __init__
    check_dangling_bonds(self)
  File "C:\...\envs\baxhax\lib\site-packages\pysb\pattern.py", line 245, in check_dangling_bonds
    check_dangling_bonds(cp)
  File "C:\...\envs\baxhax\lib\site-packages\pysb\pattern.py", line 252, in check_dangling_bonds
    raise DanglingBondError('Dangling bond(s) {} in {}'
pysb.core.DanglingBondError: Dangling bond(s) [1] in PoreFormers(bh3=1)